image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install development dependencies
    init: |
      pip install -ve . &&
      pip install -v -r dev/requirements.txt &&
      gp sync-done dev_dependencies

  - name: Build docs
    init: |
      gp sync-await dev_dependencies && 
      sphinx-build -W --keep-going -E -b html docs/ docs/_build/html
      gp sync-done build_docs

  - name: Run JupyterLab
    init: gp sync-await dev_dependencies
    command: |
      mkdir -p /workspace/.pyenv_mirror/user/current/share/jupyter/lab/settings
      cp dev/jupyterlab_settings/overrides.json /workspace/.pyenv_mirror/user/current/share/jupyter/lab/settings/overrides.json
      jupyter lab --no-browser --ip=0.0.0.0 --port=9999 --NotebookApp.token='' --NotebookApp.password=''

  - name: Run HTTP server
    init: gp sync-await build_docs
    command: cd docs/_build/html && python3 -m http.server 8000

ports:
  - name: JupyterLab
    port: 9999
    onOpen: ignore

  - name: HTTP Server
    port: 8000
    onOpen: ignore


github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false