image:
  file: .gitpod.Dockerfile

tasks:
  - name: install_lakeview
    init: | 
      pip install -ve . &&
      gp sync-done install_lakeview
  
  - name: run_notebooks
    init: | 
      gp sync-await install_lakeview
      jupyter nbconvert --to html --execute docs/examples/HG002_IGH/HG002_IGH.py.ipynb --output=HG002_IGH.py.ipynb.html
      jupyter nbconvert --to html --execute docs/examples/HG002_GNAS_WES/HG002_GNAS_WES.py.ipynb --output=HG002_GNAS_WES.py.ipynb.html
      jupyter nbconvert --to html --execute docs/examples/IGH_dot_plot/IGH_dot_plot.py.ipynb --output=IGH_dot_plot.py.ipynb.html
    
  - name: run_jupyterlab
    command: jupyter lab --no-browser --ip=0.0.0.0 --port=9999 --NotebookApp.token='' --NotebookApp.password=''

  - name: run_http_server
    command: cd docs && python -m http.server 8000

ports:
  - name: JupyterLab
    port: 9999
    onOpen: notify

  - name: HTTP Server
    port: 8000
    onOpen: ignore


github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false