image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Lakeview for development
    init: | 
      pip install -ve .

  - name: Install jupyterlab-horizon-theme
    init: pip install git+https://github.com/jzhang-dev/jupyterlab-horizon-theme

    
  - name: Run JupyterLab
    command: |
      mkdir -p /home/gitpod/.pyenv/versions/3.8.13/share/jupyter/lab/settings
      cp dev/jupyterlab_settings/overrides.json /home/gitpod/.pyenv/versions/3.8.13/share/jupyter/lab/settings/overrides.json
      jupyter lab --no-browser --ip=0.0.0.0 --port=9999 --NotebookApp.token='' --NotebookApp.password=''

  - name: Run HTTP server
    command: cd docs && python -m http.server 8000

ports:
  - name: JupyterLab
    port: 9999
    onOpen: notify

  - name: HTTP Server
    port: 8000
    onOpen: ignore


github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false