name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish_to_PyPI:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}