name: Test pip

on: [push]

jobs:
  pip_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: Test pip
      run: |
        pip install -v .
    
